name: rss-docker-build
on: workflow_dispatch
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_API_KEY }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USER }}/rss-reader:latest
          build-args: | 
            MAVEN_USER=${{ secrets.PACKAGE_USER }}
            MAVEN_PASSWORD=${{ secrets.GITHUB_TOKEN }}
          platforms: linux/arm64, linux/amd64
          

