name: Java CI

on: [push]

env:
  MAVEN_CLI_OPTS: "--settings .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_USER:  ${{ secrets.PACKAGE_USER }}
  MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  MAVEN_REPO: ${{ secrets.MAVEN_GITHUB_REPO }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: 'x64'
          cache: 'maven'
      - name: Build with Maven
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: 'x64'
          cache: 'maven'
      - name: Validate with Maven
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean verify