name: RSS READER CI/CD
on: [push]
env:
  MAVEN_CLI_OPTS: "--settings .m2/settings.xml --batch-mode"
  MAVEN_USER:  ${{ secrets.PACKAGE_USER }}
  MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: 'amd64'
          cache: 'maven'
      - run: mvn $MVN_CLI_OPTS compile

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: 'amd64'
          cache: 'maven'
      - run: mvn $MAVEN_CLI_OPTS verify